version: '3'
services:
        auth:
                image: architecture_auth
                build: ./Auth_container
                ports:
                        - "4240:4240"
                deploy:
                        mode: replicated
                        replicas: 2
        booking:
                image: architecture_booking
                build: ./Booking_container
                ports:
                      - "4241:4241"
                deploy:
                       mode: replicated
                       replicas: 2
        proto:
                image: architecture_proto
                build: ./Proto_container
                deploy:
                       mode: replicated
                       replicas: 2
        db:
                image: architecture_db
                build: ./DB_container
                ports:
                      - "4444:5432" 
                deploy:
                       mode: replicated
                       replicas: 2
        server:
               image: architecture_server
               build: ./Server_container
               ports:
                     - "4242:4242"
               deploy:
                      mode: replicated
                      replicas: 2
