kind: Service
apiVersion: v1
metadata:
  name: auth-app
  labels:
    app: auth-app
spec:
  type: NodePort
  selector:
    app: auth-app
  ports:
  - protocol: TCP
    port: 4240
    targetPort: auth
    nodePort: 31000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-app
  template:
    metadata:
      labels:
        app: auth-app
    spec:
      containers:
      - name: auth-server
        image: larilok/cms:auth-latest
        imagePullPolicy: IfNotPresent
        resources: 
          requests:
            ephemeral-storage: "100Mi"
          limits:  
            ephemeral-storage: "200Mi"
        ports:
        - name: auth
          containerPort: 4240

