kind: Service
apiVersion: v1
metadata:
  name: auth-service
  labels:
    app: auth-pod
spec:
  type: NodePort
  selector:
    app: auth-pod
  ports:
  - protocol: TCP
    port: 4240
    targetPort: auth
    nodePort: 31000
