apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-pod
  template:
    metadata:
      labels:
        app: auth-pod
    spec:
      containers:
        - name: auth-server
          image: gcr.io/rent-316614/auth
          imagePullPolicy: Always
          ports:
            - name: auth
              containerPort: 4240
