kind: Service
apiVersion: v1
metadata:
  name: auth-service
  labels:
    app: auth-pod
spec:
  selector:
    app: auth-pod
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: auth
