apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-pod
  template:
    metadata:
      labels:
        app: auth-pod
    spec:
      containers:
      - name: auth-server
        image: larilok/cms:auth-latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: auth
          containerPort: 4240

