kind: Service
apiVersion: v1
metadata:
  name: book-app
spec:
  type: NodePort
  selector:
    app: book-app
  ports:
  - protocol: TCP
    port: 4241
    targetPort: book
    nodePort: 31001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: book-app
  template:
    metadata:
      labels:
        app: book-app
    spec:
      containers:
      - name: book-server
        image: larilok/cms:book-latest
        imagePullPolicy: IfNotPresent
        resources: 
          requests:
            ephemeral-storage: "100Mi"
          limits:  
            ephemeral-storage: "200Mi"
        ports:
        - name: book
          containerPort: 4241
