kind: Service
apiVersion: v1
metadata:
  name: db-app
spec:
  selector:
    app: db-app
  ports:
  - protocol: TCP
    port: 5432
    targetPort: db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-app
  template:
    metadata:
      labels:
        app: db-app
    spec:
      containers:
      - name: db-server
        image: larilok/cms:db-latest
        imagePullPolicy: IfNotPresent
        #        command: ["/bin/sh"]
        #args: ["-c", "psql -U postgres postgres < postgres_localhost-2019_12_17_01_03_20-dump.sql"]
        ports:
        - name: db
          containerPort: 5432
