apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: posts-pod
  template:
    metadata:
      labels:
        app: posts-pod
    spec:
      containers:
        - name: posts-server
          image: gcr.io/rent-316614/posts
          imagePullPolicy: Always
          ports:
            - name: posts
              containerPort: 4242
