kind: Service
apiVersion: v1
metadata:
  name: server-app
spec:
  type: NodePort
  selector:
    app: server-app
  ports:
  - protocol: TCP
    port: 4242
    targetPort: server
    nodePort: 31002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: server-app
  template:
    metadata:
      labels:
        app: server-app
    spec:
      containers:
      - name: server-server
        image: larilok/cms:server-latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: server
          containerPort: 4242
