apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: users-pod
  template:
    metadata:
      labels:
        app: users-pod
    spec:
      containers:
        - name: users-server
          image: gcr.io/gks-cluster-316500/users
          imagePullPolicy: IfNotPresent
          ports:
            - name: users
              containerPort: 4243
