apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: users-pod
  template:
    metadata:
      labels:
        app: users-pod
    spec:
      containers:
        - name: users-server
          image: gcr.io/rent-316614/users
          imagePullPolicy: Always
          ports:
            - name: users
              containerPort: 4243
